on :
  push:
    branches:
      - main
jobs:
  deploy :
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: mkdir /opt/htdocs/doorbot || true
      - run: cp -r ./* /opt/htdocs/doorbot

          
