on :
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
        - name: show workspace
          run: |
            ls ${{ github.workspace }}
        - run: git update-index --chmod=+x ./.github/scripts/deploy.sh
        - run: bash ./.github/scripts/deploy.sh
          
