on :
  push:
    branches:
      - main
jobs:
  deploy :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
      - run: pwd
      - run: ls -al
      - run: cat ./deploy.sh
      - run: git update-index --chmod=+x ./deploy.sh
      - run: ./deploy.sh

          
