on :
  push:
    branches:
      - main
jobs:
  deploy :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git update-index --chmod=+x ./.github/scripts/deploy.sh
      - run: bash ./.github/scripts/deploy.sh

          
