on :
  push:
    branches:
      - main
jobs:
  deploy :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -al
      - run: mkdir /opt/htdocs/doorbot & cp -r * /opt/htdocs/doorbot

          
