on :
  push:
    branches:
      - main
jobs:
  deploy :
    run-on: ubuntu-latest
    steps:
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.4
        with:
          src_dir: .
          dest_dir: /opt/htdocs/doorbot
          
